workflows:
  android-build:
    name: Android Build
    environment:
      java: 17
    scripts:
      - name: Make gradlew executable and build
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
